//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYW.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelErrorMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZYW.Model.Resources.ModelErrorMessage", typeof(ModelErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不得超过{1}位 的本地化字符串。
        /// </summary>
        public static string IDLength {
            get {
                return ResourceManager.GetString("IDLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}长度不得超过{1} 的本地化字符串。
        /// </summary>
        public static string RemarkLength {
            get {
                return ResourceManager.GetString("RemarkLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}长度不得超过{1} 的本地化字符串。
        /// </summary>
        public static string XCodeLength {
            get {
                return ResourceManager.GetString("XCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必需输入 的本地化字符串。
        /// </summary>
        public static string XCodeRequired {
            get {
                return ResourceManager.GetString("XCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}路径的长度不得超过{1} 的本地化字符串。
        /// </summary>
        public static string XDepthLength {
            get {
                return ResourceManager.GetString("XDepthLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必需输入 的本地化字符串。
        /// </summary>
        public static string XDepthRequired {
            get {
                return ResourceManager.GetString("XDepthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}名称长度不得超过{1} 的本地化字符串。
        /// </summary>
        public static string XNameLength {
            get {
                return ResourceManager.GetString("XNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必需输入 的本地化字符串。
        /// </summary>
        public static string XNameRequired {
            get {
                return ResourceManager.GetString("XNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必需在{1}到{2}之间 的本地化字符串。
        /// </summary>
        public static string XOrderNumberRange {
            get {
                return ResourceManager.GetString("XOrderNumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必需指定 的本地化字符串。
        /// </summary>
        public static string XOrderNumberRequired {
            get {
                return ResourceManager.GetString("XOrderNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必需指定 的本地化字符串。
        /// </summary>
        public static string XParentIDRequired {
            get {
                return ResourceManager.GetString("XParentIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不得超过{1} 的本地化字符串。
        /// </summary>
        public static string XSourceLength {
            get {
                return ResourceManager.GetString("XSourceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必需输入 的本地化字符串。
        /// </summary>
        public static string XSourceRequired {
            get {
                return ResourceManager.GetString("XSourceRequired", resourceCulture);
            }
        }
    }
}
